version: '3.3'
services:
  backend:
    build: ./backend
    container_name: backend_flask
    restart: always
    environment:
      - APP_NAME=BackendFlaskApp
    # ports:
    #   - 8080:8080
    expose: 
      - 8080
    links:
      - db
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
  db:
    image: mysql:5.7
    restart: always
    # <Port exposed> : < MySQL Port running inside container>
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'sourcesage_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user_sourcesage'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'user_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root_password'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    # volumes:
    #   - my-db:/var/lib/mysql

# Names our volume
# volumes:
#   my-db: