"""add logo on product

Revision ID: c2956e4cf343
Revises: ccc9d9f3c5c5
Create Date: 2020-07-19 14:32:18.898844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2956e4cf343'
down_revision = 'ccc9d9f3c5c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_colors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_colors',
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=10), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
